### ISSUE TITLE
(Android) Sign-In/Register Button Too Low, No Margin

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-prototype#390] opened 2018-11-05 18:59 UTC
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

I think it sits too low, makes me think I should be able to scroll down or something because there's no space between the button and frame.

![screenshot_20181105-135515](https://user-images.githubusercontent.com/2659478/48020057-f4ea9a80-e102-11e8-9f29-d8857924f45d.png)

* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by conrad-vanl** [comment] 2018-11-06 20:31
Closing due to duplicate of #368

**Closed by conrad-vanl** 2018-11-06 20:31 UTC
