### ISSUE TITLE
Enable Location Services - Selecting a campus 

### ISSUE THREAD

**Issue by calebpanza** [ApollosProject/apollos-prototype#713] opened 2019-05-14 21:24 UTC
### Details
When when following the on-boarding process, you are asked to select your campus in order to enable Location Services. When selecting a campus location, the app throws an error.

### Expected Behavior
When you get to the on-boarding screen that asks for you campus location, I should be able to click on the option to select my campus, enable Location Services, and then from there, I should be able to slide back and forth on the options under the map until I see my campus location. From there, I should be able to click on the "Select Campus" button which will then select that as my campus.

### Actual Behavior
Follow all of the above steps _**until you reach the part where you click on the "Select Campus" button**_. Clicking on the button will throw an error.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- macOS 10.14.4
- iPhone XS Simulator (iOS 12.2)
- Xcode 10.2.1

### Steps to Reproduce
1.  Open the App and make sure you are on the Ob-Boarding Screens
2. Navigate through On-Boarding until you get to the "Select My Campus" screen
3. Click on the button to Select My Campus
4. Enable Location Services
5. Select a campus from the slider

### Stack Trace
(in the video, you will notice that I am navigating both forwards and backwards through the on-boarding process. Although the video doesn't show it, I can confirm that this does _not_ cause nor affect the error)
```2019-05-14 16:53:26.238 [error][tid:com.facebook.react.JavaScript] 'Unhandled promise rejection', { [Invariant Violation: Can't find field email on object {
  "id": "Person:a70950246f4d3563f22036aed13c9789",
  "firstName": "Caleb",
  "lastName": "Panza",
  "__typename": "Person",
  "gender": "Male",
  "birthDate": "1996-01-30T00:00:00",
  "campus": {
    "type": "id",
    "generated": false,
    "id": "Campus:Campus:a0f64573eabf00a607bec911794d50fb",
    "typename": "Campus"
  }
}.]
  framesToPop: 1,
  name: 'Invariant Violation',
  line: 286273,
  column: 30,
  sourceURL: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false' }
2019-05-14 16:53:26.238733-0400 apolloschurchapp[41211:73077817] 'Unhandled promise rejection', { [Invariant Violation: Can't find field email on object {
  "id": "Person:a70950246f4d3563f22036aed13c9789",
  "firstName": "Caleb",
  "lastName": "Panza",
  "__typename": "Person",
  "gender": "Male",
  "birthDate": "1996-01-30T00:00:00",
  "campus": {
    "type": "id",
    "generated": false,
    "id": "Campus:Campus:a0f64573eabf00a607bec911794d50fb",
    "typename": "Campus"
  }
}.]
  framesToPop: 1,
  name: 'Invariant Violation',
  line: 286273,
  column: 30,
  sourceURL: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false' }```

[on-boarding-location-error.zip](https://github.com/ApollosProject/apollos-prototype/files/3179923/on-boarding-location-error.zip)

</details>

**Comment by redreceipt** [comment] 2019-06-30 21:28
duplicate of #814

**Closed by redreceipt** 2019-06-30 21:28 UTC
Labels: bug
