### ISSUE TITLE
One Provider to rule them all...

### ISSUE THREAD

**Issue by IsaacHardy** [ApollosProject/apollos-prototype#798] opened 2019-06-17 21:15 UTC
### Description
There needs to be a single all incoposing Provider that is used within each church app and NOT held within CORE. 

### Why
Providers are created using the `react-apollo` library and many CORE modules are using their own Provider to use Apollo Client queries. This creates many issues when trying to keep all versions of the Provider in sync.

Example: NewSpring wants to update to the newest version of React Apollo, but is not able to without Core updating every provider held within the UI-Kit, UI-Auth, MediaPlayer, etc...

### Acceptance Criteria

* [ ] Keep Provider definitions in the main application and passed to each corresponding Core module.

### Possible Implementation & Open Questions
We could define the main Provider within the src/client folder in each church application and pass it down to each corresponding module.

### Other Resources

* [React-Apollo 3.0.0 PR](https://github.com/apollographql/react-apollo/pull/2892)

**Comment by conrad-vanl** [comment] 2019-06-17 22:42
`react-apollo` should be specified as a `peerDependency` in all of our packages, so that you can use any version of `react-apollo` you want. If it's not anywhere, we can open a PR.

**Comment by conrad-vanl** [comment] 2019-06-17 22:54
Do you believe this `peerDependency` setup is not working?

**Comment by IsaacHardy** [comment] 2019-06-18 01:21
I have a suspicion that the `peerDependency` isn't working as intended.

**Comment by IsaacHardy** [comment] 2019-06-18 01:25
I'd still like to discuss the need to use multiple Providers. I am not 100% clear on the practice, but it seems that having around 6 different react-apollo Providers is overkill.

**Comment by IsaacHardy** [comment] 2019-06-18 03:46
Can't we just use `ApolloConsumer` to get the `ApolloClient` instance anyways?

**Comment by vinnyjth** [comment] 2019-06-18 11:49
@IsaacHardy I only count one ApolloProvider across our whole project 🤔


Four results, but three of them are for tests. 

![image](https://user-images.githubusercontent.com/1637694/59679704-8d6af200-919d-11e9-83c8-ec9e99bd8948.png)

**Comment by vinnyjth** [comment] 2019-06-18 11:51
I'm not sure I understand the pain point / frustration that is behind this issue. I know that sharing Apollo across packages in the past has been difficult, but I think we've done a good job of using the ApolloConsumer to get the apollo `client` when needed, and using `peerDependencies` to drive the version of Apollo required.

**Comment by IsaacHardy** [comment] 2019-06-18 13:13
My main issue is this error here: 
![Simulator Screen Shot - iPhone X - 2019-06-18 at 09 08 04](https://user-images.githubusercontent.com/10745699/59684726-9d3c0380-91a8-11e9-8533-7babd19135e9.png)

There seems to be some type of inconsistency between the app Provider and the NotificationProvider held within the Providers.js

My assumption is that every external provider will have this issue since the actual error is being triggered off of the outermost component. 

Could this be an issue with the `withApollo` HOC in react-apollo 3.0.0? Sure, but it's hard to make those assumptions right now without anyway of resolving this outside of Core changes.

**Comment by vinnyjth** [comment] 2019-06-18 13:18
> Could this be an issue with the withApollo HOC in react-apollo 3.0.0? Sure, but it's hard to make those assumptions right now without anyway of resolving this outside of Core changes.

That seems likely. `withApollo` comes from `react-apollo` in version 2.5 and comes from `@apollo/react-hoc`. In version 3.0. I also know that it uses the old context API in 2.5 and the new Context API in 3.0. If you update `react-apollo` to the latest version, this package will pick up the new version of `react-apollo`, but the `notifications` package is written for version 2.5 and so I wouldn't guarantee it to work (but it should work fine if you did a minor version upgrade).

This seems like something we would take a look at when we update core to 2.5, but seeing as Apollo 3.0 isn't released yet I would hold off making major changes to the API of the core packages until we have settled on recommending 3.0 in core.

**Comment by IsaacHardy** [comment] 2019-06-18 13:25
> withApollo comes from react-apollo in version 2.5 and comes from @apollo/react-hoc

`withApollo` lives in both `react-apollo` and `@apollo/react-hoc`. So you can use it from within either module (they are exported in react-apollo from @apollo/react-hoc)

> but the notifications package is written for version 2.5 and so I wouldn't guarantee it to work (but it should work fine if you did a minor version upgrade).

This inconsistency is the reasoning for this PR. If there is any possibility that different provider packages can be built with specific versions in mind, they needs to be some "cannon" we use to determine that version. My suggestion is a "one provider to rule them all".

> I would hold off making major changes to the API of the core packages until we have settled on recommending 3.0 in core.

For NewSpring, we plan on using 3.0 as soon as its released.

**Comment by IsaacHardy** [comment] 2019-06-18 13:43
`ui-media-player` is an issue:
![Simulator Screen Shot - iPhone X - 2019-06-18 at 09 38 04](https://user-images.githubusercontent.com/10745699/59689254-543a7e00-91ad-11e9-85b8-c73ecae551fe.png)

`ui-auth` is an issue: 
![Simulator Screen Shot - iPhone X - 2019-06-18 at 09 38 47](https://user-images.githubusercontent.com/10745699/59689285-61576d00-91ad-11e9-85dd-b88ea3c247b6.png)

I'm not going any further here, I only wanted to demonstrate the potential issues we will see.

**Comment by vinnyjth** [comment] 2019-06-18 13:51
I don't think it makes sense for `core` to support different major `apollo` versions. Too much of our code is dependant on Apollo, to the point that even if we extrapolated all the provider logic (and I'm not sure what that would look like), I think we would still be opening the door to bugs and incompatibilities caused by major version differences. 

That said, if you have an an idea on how to modify core so the structure you are envisioning works, I would love to see that. Open a PR and I would gladly review / approve it assuming that it didn't contain any major breaking changes we would need to port to all the implementations.

**Comment by vinnyjth** [comment] 2019-06-26 12:08
Closing this, as I don't think we see an obvious path forward.

**Closed by vinnyjth** 2019-06-26 12:08 UTC
Labels: discussion
