### ISSUE TITLE
Login form validation/error issues

### ISSUE THREAD

**Issue by burkeshartsis** [ApollosProject/apollos-prototype#369] opened 2018-10-31 17:54 UTC
## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details
Type invalid email address without "@" or domain (.com). Expected outcome is that the email address field name slides up and shrinks. Field focuses, cursor appears, text updates as you type. Validation error appears below email input "Invalid email address". Currently, lots of inconsistency. This issue should look at all validations states.  

#### Acceptance Criteria _(Optional)_

- [ ] validation should enforce 6 character limit
- [ ] should show user friendly error messages

**Comment by redreceipt** [comment] 2018-11-19 20:09
keyboard issues: https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580

**Comment by redreceipt** [comment] 2018-11-19 22:10
@burkeshartsis validation works correctly after a failed login attempt but before that, the sign-in button is greyed out. this seems right to me, what's the intended behavior?

**Comment by conrad-vanl** [comment] 2019-01-15 20:34
Closing due to we should not do client-side validation in this case.

**Closed by conrad-vanl** 2019-01-15 20:34 UTC
